
server.port=8080

# Cấu hình Neon DB
spring.datasource.url=jdbc:postgresql://ep-weathered-river-ap9qvafu-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Giữ nguyên cấu hình cũ
mqtt.broker=ssl://5420b4b5ac634d40a88e755f61f76da2.s1.eu.hivemq.cloud:8883
mqtt.username=flutter_user
mqtt.password=${MQTT_PASSWORD}
mqtt.clientId=fire-iot-backend
mqtt.telemetryTopic=firealarm/esp32_01/telemetry
mqtt.controlTopic=firealarm/esp32_01/control

twilio.accountSid=${TWILIO_SID}
twilio.authToken=${TWILIO_TOKEN}
twilio.toNumber=+84368543552
twilio.fromNumber=+19382537209
twilio.statusCallbackUrl=https://spinaceous-unregulable-alessandra.ngrok-free.dev/api/twilio/call-status